#SITE_NAME|REPO_LINK|PORT
#eletricmotor|https://github.com/Git-iEng/electricmotor.git|8009
#controlandautomation|https://github.com/Git-iEng/controlandauto.git|8011
#transformeroil|https://github.com/Git-iEng/transformer_oil_filter.git|8013
#battery|https://github.com/Git-iEng/battery.git|8014
#airbreakswtich|https://github.com/Git-iEng/airbreakswtich.git|8015
#ricemill|https://github.com/Git-iEng/ricemill.git|8016
#terminationkit|https://github.com/Git-iEng/terminationkit.git|8017
#steelmill|https://github.com/Git-iEng/steelmill.git|8018
#heatingequipment|https://github.com/Git-iEng/heatingequipment.git|8019
#lvhvmvpanel|https://github.com/Git-iEng/lvhvpanel.git|8020
#powercable1|https://github.com/Git-iEng/powercable.git|8021
#powerqualitysolution|https://github.com/Git-iEng/powerqualitysolution.git|8022
#generator|https://github.com/Git-iEng/generator.git|8023
#containersolution|https://github.com/Git-iEng/containersolution.git|8024
#generators|https://github.com/Git-iEng/generators.git|8023
#neplan|https://github.com/Git-iEng/Neplan.git|8002
#boiler|https://github.com/Git-iEng/boiler.git|8012
#xgslab|https://github.com/Git-iEng/xgslab.git|8005
